config/routes.rb
App::Application.routes.draw do

  resources :recommendations_auditees

  resources :recommendations_documents

  resources :recommendations_dependencies

  resources :recommendations_compliances

  resources :auditactions

  resources :recommendations

  resources :audits

  resources :reports

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards








  root :to => 'dashboards#index'


end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  attr_accessible :auditrecommendations, :closeddate, :compliancetopic, :primarytopic, :priority, :reference, :secondarytopic, :severity, :status, :targetdate, :title, :verification
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recommendations }
    end
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommendation }
    end
  end

  # GET /recommendations/new
  # GET /recommendations/new.json
  def new
    @recommendation = Recommendation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommendation }
    end
  end

  # GET /recommendations/1/edit
  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(params[:recommendation])

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render json: @recommendation, status: :created, location: @recommendation }
      else
        format.html { render action: "new" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommendations/1
  # PUT /recommendations/1.json
  def update
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      if @recommendation.update_attributes(params[:recommendation])
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy

    respond_to do |format|
      format.html { redirect_to recommendations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_form.html.erb
<html>
<head>
  <script>
  $(function() {
     $( "#datepicker" ).datepicker({
      dateFormat: "yy-mm-dd",
      showOn: "button",
      buttonImage: "/images/calendar.jpg",
      buttonImageOnly: true
    });
     $( "#datepicker1" ).datepicker({
      dateFormat: "yy-mm-dd",
      showOn: "button",
      buttonImage: "/images/calendar.jpg",
      buttonImageOnly: true
    });
      });
  </script>
</head>
<body>
<%= form_for(@recommendation) do |a| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="span11 offset well">
  <div class="form-horizontal">
    <div class="accordion " id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            New Recomondation 
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">
            <div class="control-group">
    <%= a.label :title %><br />
    <%= a.text_field :title , :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :status %><br />
    <%= a.select :status ,[['Opened','Opened'],['risk accepted','risk accepted'],['closed','closed'],['closed duplicate','closed duplicate']], :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :auditorrecommendations%><br />
    <%= a.text_field :auditrecommendations , :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :reference %><br />
    <%= a.text_field :reference , :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :primarytopic %><br />
    <%= a.select :primarytopic ,[['access','access'],['network','network'],['premises','premises'],['management','management'],['global','gloabal'],['monitoring','monitoring']], :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :secondarytopic %><br />
    <%= a.select :secondarytopic ,[['access','access'],['network','network'],['premises','premises'],['management','management'],['global','gloabal'],['monitoring','monitoring']], :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :compliancetopic %><br />
    <%= a.text_field :compliancetopic , :required => true %>
  </div>
            <div class="control-group">
              <input type="checkbox">verified</input>
            </div>
            <div class="control-group">
    <%= a.label :priority %><br />
    <%= a.select :priority ,[['low','low'],['medium','medium'],['high','high']], :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :severity %><br />
    <%= a.select :severity ,[['low','low'],['medium','medium'],['high','high']], :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :targetdate %><br />
    <%= a.text_field :targetdate, :id => :datepicker , :required => true %>
  </div>
            <div class="control-group">
    <%= a.label :closeddate %><br />
    <%= a.text_field :closeddate, :id => :datepicker1 , :required => true %>
  </div>
</div>
</div>
</div>
</div>
</div>
<br>
<div>
    <%= a.submit 'Create Recommondation', :class => "pure-button pure-button-primary" %>
    <%= link_to 'Cancel', policies_path, :class => "pure-button pure-button-primary" %>
  </div>
<% end %>
</div>
</body>
</html>

app/views/recommendations/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well"> 
				<h1>Editing Recommondation</h1>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>
</html>

app/views/recommendations/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Auditor" data-toggle="tab">Auditor</a></li>
                        <li><a href="#Auditee" data-toggle="tab">Auditee</a></li>                        
                        <li><a href="#Per" data-toggle="tab">Permieeee</a></li>
                        <li><a href="#Document" data-toggle="tab">Document</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Auditor" class="tab-pane active">
                            <table class="table table-bordered">
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Severity</th>
  </tr>

<% @recommendations.each do |recommendation| %>
  <tr>
    <td><%= recommendation.title %></td>
    <td><%= recommendation.status %></td>
    <td><%= recommendation.severity %></td>
    <td><%= link_to 'Show', recommendation %></td>
    <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
    <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recommendation', new_recommendation_path, :class => "pure-button pure-button-primary" %>
</div>


<div id="Auditee" class="tab-pane">
</div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/views/recommendations/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<%= render 'form' %>
			<br>
		</div>
	</div>
</body>
</html>

app/views/recommendations/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @recommendation.title %>
</p>

<p>
  <b>Status:</b>
  <%= @recommendation.status %>
</p>

<p>
  <b>Auditrecommendations:</b>
  <%= @recommendation.auditrecommendations %>
</p>

<p>
  <b>Reference:</b>
  <%= @recommendation.reference %>
</p>

<p>
  <b>Primarytopic:</b>
  <%= @recommendation.primarytopic %>
</p>

<p>
  <b>Secondarytopic:</b>
  <%= @recommendation.secondarytopic %>
</p>

<p>
  <b>Compliancetopic:</b>
  <%= @recommendation.compliancetopic %>
</p>

<p>
  <b>Verification:</b>
  <%= @recommendation.verification %>
</p>

<p>
  <b>Priority:</b>
  <%= @recommendation.priority %>
</p>

<p>
  <b>Severity:</b>
  <%= @recommendation.severity %>
</p>

<p>
  <b>Targetdate:</b>
  <%= @recommendation.targetdate %>
</p>

<p>
  <b>Closeddate:</b>
  <%= @recommendation.closeddate %>
</p>
<%= link_to 'Edit', edit_recommendation_path(@recommendation), :class => "pure-button pure-button-primary" %>
<%= link_to 'Back', recommendations_path, :class => "pure-button pure-button-primary" %>
</div>
</div>
</body>
</html>