config/routes.rb
App::Application.routes.draw do

  resources :recommendations_auditees

  resources :recommendations_documents

  resources :recommendations_dependencies

  resources :recommendations_compliances

  resources :auditactions

  resources :recommendations

  resources :audits

  resources :reports

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards








  root :to => 'dashboards#index'


end

app/models/businessunit.rb
class Businessunit < ActiveRecord::Base
  attr_accessible :b_area, :b_city, :b_country, :b_name, :b_site, :b_state ,:time_zone
  has_many :policies 
end

app/controllers/businessunits_controller.rb
class BusinessunitsController < ApplicationController
  # GET /businessunits
  # GET /businessunits.json
  def index
    @businessunits = Businessunit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businessunits }
    end
  end

  # GET /businessunits/1
  # GET /businessunits/1.json
  def show
    @businessunit = Businessunit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @businessunit }
      format.pdf do
        pdf = BusinessunitsPdf.new(@businessunit)
        send_data pdf.render , filename: "#{@businessunit.b_name}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /businessunits/new
  # GET /businessunits/new.json
  def new
    @businessunit = Businessunit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @businessunit }
    end
  end

  # GET /businessunits/1/edit
  def edit
    @businessunit = Businessunit.find(params[:id])
  end

  # POST /businessunits
  # POST /businessunits.json
  def create
    @businessunit = Businessunit.new(params[:businessunit])

    respond_to do |format|
      if @businessunit.save
        format.html { redirect_to @businessunit, notice: 'Businessunit was successfully created.' }
        format.json { render json: @businessunit, status: :created, location: @businessunit }
      else
        format.html { render action: "new" }
        format.json { render json: @businessunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businessunits/1
  # PUT /businessunits/1.json
  def update
    @businessunit = Businessunit.find(params[:id])

    respond_to do |format|
      if @businessunit.update_attributes(params[:businessunit])
        format.html { redirect_to @businessunit, notice: 'Businessunit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @businessunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businessunits/1
  # DELETE /businessunits/1.json
  def destroy
    @businessunit = Businessunit.find(params[:id])
    @businessunit.destroy

    respond_to do |format|
      format.html { redirect_to businessunits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/businessunits_helper.rb
module BusinessunitsHelper
end

app/views/businessunits/_form.html.erb
<%= form_for(@businessunit) do |f| %>
<% if @businessunit.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@businessunit.errors.count, "error") %> prohibited this businessunit from being saved:</h2>

  <ul>
    <% @businessunit.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="span11 offset well">
  <div class="form-horizontal">

    <div class="control-group">
      <%= f.label "Business Unit" %>
      <%= f.text_field :b_name %>
    </div>
    <div class="control-group">
      <%= f.label "Site" %>
      <%= f.text_field :b_site %>
    </div>
    <div class="control-group">
      <%= f.label "Area" %>
      <%= f.text_field :b_area %>
    </div>
    <div class="control-group">
      <%= f.label "City" %>
      <%= f.text_field :b_city %>
    </div>
    <div class="control-group">
      <%= f.label 'State' %>
      <%= f.text_field :b_state %>
    </div>
    <div class="control-group">
      <%= f.label 'Country' %>
      <%= f.text_field :b_country %>
    </div>
    <div class="control-group">
      <b> Timezone </b><br/>
      <%= f.time_zone_select :time_zone , ActiveSupport::TimeZone.all %>
    </div>
    <div class="control-group">
      <%= f.submit 'Create BU', :class => "pure-button pure-button-primary"%>
      <%= link_to 'Cancel', businessunits_path , :class => "pure-button pure-button-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/businessunits/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/businessunits/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
<!--                     <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Policy</a></li>
                    </ul>
 -->                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">

                            <table class="table table-bordered">
                              <tr>
                                <th>Business Unit</th>
                                <th>Site</th>
                                <th>Country</th>
                            </tr>

                            <% @businessunits.each do |businessunit| %>
                            <tr>
                                <td><%= businessunit.b_name %></td>
                                <td><%= businessunit.b_site %></td>
                                <td><%= businessunit.b_country %></td>
                                <td><%= link_to 'Show', businessunit %></td>
                                <td><%= link_to 'Destroy', businessunit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                            <% end %>
                        </table>

                        <br />

                        <%= link_to 'New Businessunit', new_businessunit_path , :class => "pure-button pure-button-primary"  %>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>





app/views/businessunits/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/businessunits/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

      <p>
        <b>Business Unit</b>
        <%= @businessunit.b_name %>
      </p>

      <p>
        <b>Site</b>
        <%= @businessunit.b_site %>
      </p>

      <p>
        <b>Area</b>
        <%= @businessunit.b_area %>
      </p>

      <p>
        <b>City</b>
        <%= @businessunit.b_city %>
      </p>

      <p>
        <b>State</b>
        <%= @businessunit.b_state %>
      </p>

      <p>
        <b>Country</b>
        <%= @businessunit.b_country %>
      </p>

      <%= link_to "Show Report", businessunit_path(@businessunit, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_businessunit_path(@businessunit) , :class => "pure-button pure-button-primary" %> 
      <!--      <%= link_to 'Back', businessunits_path , :class => "pure-button pure-button-primary" %> -->

      <%= link_to 'New Businessunit', new_businessunit_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>