config/routes.rb
App::Application.routes.draw do

  resources :recommendations_auditees

  resources :recommendations_documents

  resources :recommendations_dependencies

  resources :recommendations_compliances

  resources :auditactions

  resources :recommendations

  resources :audits

  resources :reports

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards








  root :to => 'dashboards#index'


end

app/models/recommendations_dependency.rb
class RecommendationsDependency < ActiveRecord::Base
  attr_accessible :duplicatereco, :recommendations, :title
end

app/controllers/recommendations_dependencies_controller.rb
class RecommendationsDependenciesController < ApplicationController
  # GET /recommendations_dependencies
  # GET /recommendations_dependencies.json
  def index
    @recommendations_dependencies = RecommendationsDependency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recommendations_dependencies }
    end
  end

  # GET /recommendations_dependencies/1
  # GET /recommendations_dependencies/1.json
  def show
    @recommendations_dependency = RecommendationsDependency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommendations_dependency }
    end
  end

  # GET /recommendations_dependencies/new
  # GET /recommendations_dependencies/new.json
  def new
    @recommendations_dependency = RecommendationsDependency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommendations_dependency }
    end
  end

  # GET /recommendations_dependencies/1/edit
  def edit
    @recommendations_dependency = RecommendationsDependency.find(params[:id])
  end

  # POST /recommendations_dependencies
  # POST /recommendations_dependencies.json
  def create
    @recommendations_dependency = RecommendationsDependency.new(params[:recommendations_dependency])

    respond_to do |format|
      if @recommendations_dependency.save
        format.html { redirect_to @recommendations_dependency, notice: 'Recommendations dependency was successfully created.' }
        format.json { render json: @recommendations_dependency, status: :created, location: @recommendations_dependency }
      else
        format.html { render action: "new" }
        format.json { render json: @recommendations_dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommendations_dependencies/1
  # PUT /recommendations_dependencies/1.json
  def update
    @recommendations_dependency = RecommendationsDependency.find(params[:id])

    respond_to do |format|
      if @recommendations_dependency.update_attributes(params[:recommendations_dependency])
        format.html { redirect_to @recommendations_dependency, notice: 'Recommendations dependency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommendations_dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations_dependencies/1
  # DELETE /recommendations_dependencies/1.json
  def destroy
    @recommendations_dependency = RecommendationsDependency.find(params[:id])
    @recommendations_dependency.destroy

    respond_to do |format|
      format.html { redirect_to recommendations_dependencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recommendations_dependencies_helper.rb
module RecommendationsDependenciesHelper
end

app/views/recommendations_dependencies/_form.html.erb
<%= form_for(@recommendations_dependency) do |f| %>
  <% if @recommendations_dependency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendations_dependency.errors.count, "error") %> prohibited this recommendations_dependency from being saved:</h2>

      <ul>
      <% @recommendations_dependency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :recommendations %><br />
    <%= f.text_field :recommendations %>
  </div>
  <div class="field">
    <%= f.label :duplicatereco %><br />
    <%= f.text_field :duplicatereco %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recommendations_dependencies/edit.html.erb
<h1>Editing recommendations_dependency</h1>

<%= render 'form' %>

<%= link_to 'Show', @recommendations_dependency %> |
<%= link_to 'Back', recommendations_dependencies_path %>

app/views/recommendations_dependencies/index.html.erb
<h1>Listing recommendations_dependencies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Recommendations</th>
    <th>Duplicatereco</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recommendations_dependencies.each do |recommendations_dependency| %>
  <tr>
    <td><%= recommendations_dependency.title %></td>
    <td><%= recommendations_dependency.recommendations %></td>
    <td><%= recommendations_dependency.duplicatereco %></td>
    <td><%= link_to 'Show', recommendations_dependency %></td>
    <td><%= link_to 'Edit', edit_recommendations_dependency_path(recommendations_dependency) %></td>
    <td><%= link_to 'Destroy', recommendations_dependency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recommendations dependency', new_recommendations_dependency_path %>

app/views/recommendations_dependencies/new.html.erb
<h1>New recommendations_dependency</h1>

<%= render 'form' %>

<%= link_to 'Back', recommendations_dependencies_path %>

app/views/recommendations_dependencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @recommendations_dependency.title %>
</p>

<p>
  <b>Recommendations:</b>
  <%= @recommendations_dependency.recommendations %>
</p>

<p>
  <b>Duplicatereco:</b>
  <%= @recommendations_dependency.duplicatereco %>
</p>


<%= link_to 'Edit', edit_recommendations_dependency_path(@recommendations_dependency) %> |
<%= link_to 'Back', recommendations_dependencies_path %>