config/routes.rb
App::Application.routes.draw do

  resources :recommendations_auditees

  resources :recommendations_documents

  resources :recommendations_dependencies

  resources :recommendations_compliances

  resources :auditactions

  resources :recommendations

  resources :audits

  resources :reports

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards








  root :to => 'dashboards#index'


end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :duedate, :executivesummary, :source, :status, :subtitle, :title, :audit_id
  belongs_to :audit
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @audit = Audit.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit

    @report = Report.find(params[:id])
    @audit = Audit.find(:all)
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<html>
<head>
  <script>
  $(function() {
     $( "#datepicker" ).datepicker({
      dateFormat: "yy-mm-dd",
      showOn: "button",
      buttonImage: "/images/calendar.jpg",
      buttonImageOnly: true
    });
  });
  </script>
</head>
<body>

<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="span11 offset well">
  <div class="form-horizontal">
    <div class="accordion " id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            New Report 
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">


            <div class="control-group">
              <%= f.label :AuditReference %><br />
              <%= f.collection_select :audit_id , @audit, :id ,:reference %>
            </div>

            <div class="new-two">
              <%= f.label :origin %>
            </div>

            <div class="new-one">
              <%= f.label :topic %><br/><br>
            </div>

            <div class="new-two">
              <%= f.label :title %><br />
              <%= f.text_field :title , :required => true %>
            </div>
            <div class="new-one">
              <%= f.label :subtitle %><br />
              <%= f.text_field :subtitle , :required => true %>
            </div>
            <div class="control-group">
            <%= f.label :executivesummary %><br />
            <%= f.text_area :executivesummary %>
          </div>
          <div class="control-group">
            <%= f.label :source %><br />
            <%= f.text_field :source , :required => true %>
          </div>
          <div class="control-group">
            <%= f.label :duedate %><br />
            <%= f.text_field :duedate, :id => :datepicker , :required => true %>
          </div>
          <div class="control-group">
            <%= f.label :status %><br />
            <%= f.select :status , [["Draft","draft"],["Final","final"],["Approved","approved"],["Published","published"]], :required => true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<div>
  <%= f.submit 'Create Report',:class => "pure-button pure-button-primary" %>
  <%= link_to 'Cancel', reports_path, :class => "pure-button pure-button-primary" %>
</div>
<% end %>
</div>
</body>
</html>

app/views/reports/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well"> 
				<h1>Editing Reports</h1>
				<%= render 'form' %>
				<%= link_to 'Show', @report %> |
				<%= link_to 'Back', reports_path %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/reports/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Reports" data-toggle="tab">Reports</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">
                            <table class="table table-bordered">
                              <tr>
                                  <th>Title</th>
                                  <th>Duedate</th>
                                  <th>Status</th>
                              </tr>
                              <% @reports.each do |report| %>
                              <tr>
                                <td><%= report.title %></td>
                                <td><%= report.duedate %></td>
                                <td><%= report.status %></td>
                                <td><%= link_to 'Show', report %></td>
                                <td><%= link_to 'Edit', edit_report_path(report) %></td>
                                <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                            <% end %>
                        </table>
                        <br />
                        <%= link_to 'New Report', new_report_path, :class => "pure-button pure-button-primary" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/views/reports/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<%= render 'form' %>		
			<br>
		</div>
	</div>
</body>
</html>

app/views/reports/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
<p id="notice"><%= notice %></p>

<p>
  <b>AuditReference:</b>
  <%= @report.audit_id %>
</p>


<p>
  <b>Title:</b>
  <%= @report.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @report.subtitle %>
</p>

<p>
  <b>Executivesummary:</b>
  <%= @report.executivesummary %>
</p>

<p>
  <b>Source:</b>
  <%= @report.source %>
</p>

<p>
  <b>Duedate:</b>
  <%= @report.duedate %>
</p>

<p>
  <b>Status:</b>
  <%= @report.status %>
</p>


<%= link_to 'Edit', edit_report_path(@report), :class => "pure-button pure-button-primary" %>
<%= link_to 'Back', reports_path, :class => "pure-button pure-button-primary" %>
</div>
</div>
</body>
</html>